In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.arange(12.).reshape(3, 4)

In [3]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [4]:
arr[0]

array([0., 1., 2., 3.])

In [5]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [6]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [7]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [8]:
frame.iloc[0]

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [9]:
series = frame.iloc[0]

In [10]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [11]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [12]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [13]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])

In [14]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [15]:
series3 = frame['d']

In [16]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [17]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [18]:
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0